SmabaPOSHelp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from mails import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inbox),
    path('mails/', include('mails.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'
urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    re_path(r'^login/$', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

]

mails/urls.py
from django.urls import path, re_path
from . import views

app_name = 'mails'
urlpatterns = [
    path('inbox/', views.inbox, name='inbox'),
    #path('outbox/', views.outbox, name='outbox'),
    #path('create/', views.create, name='create'),
    #path('delete/', views.delete, name='delete'),
    #path('delete/<str:back>/', views.delete, name='delete'),
    #path('forward/', views.forward, name='forward'),
    #path('ajax_new_message/', views.new_message, name='new_message'),
    # path('send-mail',views.sendMail, name='sendMail' ),
    re_path(r"detail-mail/(?P<uid>[\w '-]+)/(?P<reply>[\w']+)/$", views.detail, name='detailMail'),
    #re_path(r"create/(?P<uid>[\w']+)/(?P<reply>[\w']+)/$", views.create, name='create'),

]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from mails.models import Person


class myUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(myUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control mb-0'
        self.fields['username'].label = "Kullanıcı Adı"
        self.fields['username'].help_text = "<small>30 karakterden az, Harf, sayı ve '@/./+/-/_' içerebilir.</small>"
        self.fields['password1'].widget.attrs['class'] = 'form-control mb-0'
        self.fields['password1'].label = "Şifre"
        self.fields[
            'password1'].help_text = "<small><ul><li>Şifreniz minimum sekiz karekter olmalı</li><li>Harf içermelidir</li></ul></small>"
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].label = "Şifre Tekrarı"
        self.fields['password2'].help_text = "<small>Kontrol için şifrenizi tekrar giriniz</small>"


class myAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(myAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control mb-0'
        self.fields['username'].label = "Kullanıcı Adı"
        self.fields['username'].error_messages = {'invalid': 'Lütfen kullanıcı adınızı ve şifrenizi kontrol edin!'}
        self.fields['password'].widget.attrs['class'] = 'form-control mb-0'
        self.fields['password'].label = "Şifre"
        self.fields['password'].error_messages = {'invalid': 'Lütfen kullanıcı adınızı ve şifrenizi kontrol edin!'}

# class createPersonForm(forms.ModelForm):
#    class Meta:
#        model=Person
#        fields = ('username', 'password')

#    def __init__(self, *args, **kwargs):
#        super(createPersonForm, self).__init__(*args, **kwargs)
#        self.fields['username'].widget.attrs['class'] = 'form-control mb-0'
#        self.fields['username'].label ="Kullanıcı Adı"
#        self.fields['username'].error_messages={'invalid':'Lütfen kullanıcı adınızı ve şifrenizi kontrol edin!'}
#        self.fields['password'].widget.attrs['class'] = 'form-control mb-0'
#        self.fields['password'].label ="Şifre"
#        self.fields['password'].error_messages={'invalid':'Lütfen kullanıcı adınızı ve şifrenizi kontrol edin!'}

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout

from .forms import myUserCreationForm, myAuthenticationForm
from mails.models import Person


def signup_view(request):
    if request.method == 'POST':
        form = myUserCreationForm(request.POST)
        print(form.data['firstName'])
        if form.is_valid():
            # save() user dönüyor. onu login yapıyoruz
            user = form.save()
            # mailbox oluştur

            person = Person(person=user, first_name=form.data['firstName'], last_name=form.data['lastName'],
                            personColor=form.data['color'])
            person.save()
            # LOGIN
            login(request, user)
            return redirect('mails:inbox')
    else:
        form = myUserCreationForm()
    return render(request, 'account/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = myAuthenticationForm(data=request.POST)
        if form.is_valid():
            # form dan user'ı alıyorum
            user = form.get_user()
            # LOGIN
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('mails:inbox')
    else:
        form = myAuthenticationForm()
    return render(request, 'account/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('account:login')

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel='stylesheet' href='/static/style.css'>-->
    
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel='stylesheet' href="{% static 'p_style.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-sm ">         
        <a href='/#' class="navbar-brand col-2 text-dark"><img  height="30px" width="auto" src="{% static 'sambalogo.png' %}" alt=''></a>
        {% if user.is_authenticated %}
        <input class="form-control mr-sm-2" type="search" placeholder="Ara...">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0" action="{% url 'account:logout' %}" method="POST">
                        {% csrf_token%}
                        <button type='submit' class="btn btn-outline-info" >Logout</button>
                        {{avatar.full_name}}
                    </form>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0 ">
                <li class="nav-item mr-2"><a class="nav-link btn btn-outline-info" href="{% url 'account:login' %}" class="nav-link" >Login</a></li>
                <li class="nav-item "><a class="nav-link btn btn-outline-info" href="{% url 'account:signup' %}" class="nav-link" >Signup</a></li>
            </ul>
        {% endif %}
    </nav>
    <div class="container-fluid  d-flex mt-0">
        {% if user.is_authenticated %}
        <div class="container col-2 border main">
            <nav class='nav flex-column mt-2' >
                <a class="nav-link text-dark side_bar_menu" href="{% url 'mails:inbox' %}" ><b>Gelen Mesajlar</b></a><br>
                <a class="nav-link text-dark side_bar_menu" href="" ><b>Gönderilen Mesajlar</b></a><br>
                <a class="nav-link text-dark side_bar_menu" href=""><b>Yeni Mesaj Oluştur </b></a>
            </nav>
        </div>
        {% endif %}
        <div class="container col-10 border main position-relative   ">
            {% block content %}
            {% endblock %}
        </div>
        
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript">
//    setInterval(()=>{
//    $.ajax({
//        url: "",
//        type:  'GET',
//        dataType: 'json',
//        success: function (data) {
//        
//         addNewMessage(JSON.parse(data['new_msg']))   
//         //for(var i=0 ; i< data[1].length ; i++){
//         //    console.log(JSON.stringify(data[1][i]))
//         //}
//
//        }
//      })},
//      50000);
//    function addNewMessage(data_object){
//        for(var i = 0; i<data_object.length ; i++){
//            var data = data_object[i]['fields'];
//            var id_li='d';
//            var prepend_id_li = '#d';
//            var id_link='f';
//            var prepend_id_link = '#f';
//            var mailDate =new Date(Date.parse(data.date));
//            var deneme= `<li class="list-group-item p-0">
//                    <a  class='row text-info p-2'
//                    href="/mails/detail-mail/${data.uid}/notReply")>
//                        <input class='col-1 list__checkbox m-auto' name='message_checkbox_inbox' value="${data.uid}" type="checkbox">
//                        <p class="col-2 list__name text-truncate ">${data.from_name}</p>
//                        <p class="col-4 list__subject text-truncate text-truncate ">${data.subject}</p>
//                        <div class="col-3 d-flex " >
//                        </div>
//                        <p class="col-2 list__date">${mailDate.getDate()}/${mailDate.getMonth()}/${mailDate.getFullYear()} ${mailDate.getHours()}:${mailDate.getMinutes()}</p>
//                    </a>
//                </li>`
//            $('#incoming').prepend(deneme);
//        }
//    }
//    function submitFormToDelete(e){
//        $('#delete_modal').hide()
//        console.log(e)
//        $.ajax({
//            type:'POST',
//            url:"",
//            data : $(`#${e.name}`).serialize(),
//            success: (event)=>{
//                $(`#${e.name} a`).each(function() {
//                     if($(this).find('input').is(":checked"))
//                         $(this).hide();
//                });
//            }
//        })
//    };
//
    console.log(window.location,"windows location");
    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/newMail/');
    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);

        console.log(data,"chat socket on message")
    }

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };



</script>
{% block page %}

{% endblock %}
</html>